title: freethejazz
description: Tech blog

url: http://freethejazz.github.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

gems: [ 'jekyll-paginate' ]

markdown: redcarpet
highlighter: pygments
paginate: 5

kramdown:
  input: GFM

navigation:
 - title: Home
   url: /index.html
 - title: Experiments
   url: /experiments.html

collections:
  experiments:
    output: true
    permalink: /experiments/:path/

social:
   github: freethejazz
   twitter: freethejazz
   email: freethejazz@gmail.com

google_analytics: "UA-38041063-3"
